###
GET localhost:8080/products?categories=Software&categories=Beauty&categories=Books&categories=Jewelry&categories=Baby&categories=Musical+Instruments&categories=Category+20&categories=Grocery

###
GET localhost:8080/products/2

###
GET localhost:8080/categories

###
GET localhost:8080/products/prices