###
GET localhost:8080/products

###
GET localhost:8080/products?page=5&sortBy=products.updated_at&sortOrder=desc

###
GET localhost:8080/products?categories=Books&preloadCategories=true

###
GET localhost:8080/categories

###
GET localhost:8080/products/prices

###
GET localhost:8080/reviews

###
POST localhost:8080/login
Content-Type: Application/json

{
  "Identifier": "admin@nhannht.kute",
  "Password": "admin123"
}

###
GET http://localhost:8080/test
Content-Type: Application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjUwNDEwMDcsInVzZXJfaWQiOjF9.esfiOu0-PGZXPLAo2-LC5CEHZUOB1Nh2sQSf9MwbE4s

###
GET http://localhost:8080/orders?sortBy=updated_at&sortOrder=desc&preload=OrderItems.Product